networks:
  cluster:

services:
  # Clickhouse database
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    user: "$UID:$GID"
    hostname: clickhouse
    networks: [cluster]
    environment:
      - CLICKHOUSE_DB=${AKAI_CH_DB:-akai_default}
      - CLICKHOUSE_USER=${AKAI_CH_USER:-username}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=${AKAI_CH_PASSWORD:-password}
    volumes:
      - ./external/db/clickhouse_avail/data:/var/lib/clickhouse/
      - ./external/db/clickhouse_avail/logs:/var/log/clickhouse-server/
    ports:
      - "${CH_HTTP_PORT:-8123}:8123"
      - "${CH_NATIVE_PORT:-9000}:9000"
      - "${CH_SQL_PORT:-9005}:9005"
    healthcheck: # executed inside the container
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping
      interval: 5s

  # Prometheus for real-time metrics
  prometheus:
    image: prom/prometheus:latest
    user: "${UID}:${GID}"
    networks: [cluster]
    volumes:
      - ./external/prometheus/:/etc/prometheus/
      - ./external/db/prometheus:/prometheus/data
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.listen-address=${PROMETHEUS_ADDRESS:-localhost:9090}"
      - "--storage.tsdb.retention.time=1y"
      - "--web.enable-remote-write-receiver"
    ports:
      - "9090:9090"
