name: Go Tests

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  CH_USER: username
  CH_PASSWORD: password
  CH_DATABASE: akai_test

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    services:
      clickhouse:
        image: clickhouse/clickhouse-server
        env:
          CLICKHOUSE_DB: ${{ env.CH_DATABASE }}
          CLICKHOUSE_USER: ${{ env.CH_USER }}
          CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
          CLICKHOUSE_PASSWORD: ${{ env.CH_PASSWORD }}
        ports:
          - "127.0.0.1:8123:8123"
          - "127.0.0.1:9000:9000"

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: extractions/setup-just@v3
        with:
          just-version: "1.40.0"

      - name: Build Tool
        run: just build

      - name: Run tests
        run: |
          just test
          # TODO:
          # - removing the db test, as the integration of Akai with the production
          # Clickhouse (and the ReplicatedMergedTree) is failing
          # - needs to be checked up
          # make test-db
